version: '3.7'
services: 
  api:
    container_name: api
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    ports:
      - "8000:8000"
  nginx:
    depends_on: 
    - api
    container_name: ngnix
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports: 
      - "80:80"
    restart: always