[project]
name = "fastapi-with-react"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
  "fastapi==0.125.0",
  "gunicorn==26.0.0",
  "passlib==1.7.4",
  "pydantic-settings>=2.14.2",
  "pydantic[email]==2.13",
  "pymongo==4.17.0",
  "python-jose==3.3.0",
  "uvicorn==0.49.0",
]

[dependency-groups]
dev = ["pyright>=1.1.411", "ruff>=0.15.20", "ty>=0.0.55"]
